# Install pre-commit hooks via
# pre-commit install

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    # - id: check-json
    # - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  # takes too long
  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: "0.46"
  #   hooks:
  #   - id: check-manifest
  #     # args: [--no-build-isolation]
  #     # additional_dependencies: [setuptools>=46.4.0]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==21.3.1]
      exclude: >
          (?x)^(docker/status.py|)$
